from .edit import executeEdit
from .echo import executeEcho
from .help import executeHelp
from .clear import clearScreen
from .touch import executeTouch
from .cd import executeCd
from .mkdir import executeMkdir
from .pwd import executePwd
from .ls import executeLs
from .rm import executeRm
from .cat import executeCat
from .eval import executeEval
from .neofetch import executeNeofetch
